packages:
  - 'vite-plugin-ssr/'
  - 'docs/'
  - 'boilerplates/'
  - 'boilerplates/*'
  - 'examples/*'
  - 'examples/framework/*'
  - 'examples/renderer/*'
  - 'libframe/test/'
  - 'libframe/docs/'
  - 'libframe/scripts/'
