name: "💥 Bug Report"
description: Report a bug.
labels: ["bug :boom:"]
body:
  - type: markdown
    attributes:
      value: |
        > We have this error/problem with tool X, can you help?
        
        :red_circle: **Bad**: Ask tool X instead of asking us. Only ask us if you believe your problem to be related to vite-plugin-ssr.
        > Our app is broken and we don't know why, can you help?
        
        :red_circle: **Bad**: We won't help with problems unrelated to vite-plugin-ssr. Only ask us if you have evidence that your problem is related to vite-plugin-ssr.
        > We have this error originating from vite-plugin-ssr.
        
        :green_circle: **Good**: Post the error message and error stack, we'll start fixing the error right away (usually under 24 hours).
  - type: textarea
    attributes:
      label: Description
      description: "Describe the bug. Optional: an Error Stack originating from vite-plugin-ssr is usually enough."
  - type: textarea
    attributes:
      render: shell
      label: Error Message + Error Stack
