name: "Bug Report"
description: Report a bug.
labels: ["Bug :boom:"]
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: Describe the bug. Optional: the error stack is usually enough.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description 2
      description: "bla"
    validations:
      required: true
