name: ":boom: Bug Report"
description: Report a bug.
labels: ["Bug :boom:"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the bug. Optional: the error stack is usually enough.
  - type: textarea
    attributes:
      label: Error Stack
      description: Bugs usually throw an error. Paste the full error stack here.
