name = "vite-plugin-ssr_worker-example"
main="./worker/index.js"
compatibility_date = "2021-09-29"
workers_dev = true
node_compat = true
compatibility_flags = ["streams_enable_constructors"]

[site]
bucket = "./dist/client"

[dev]
port = 3000
