name: CI Discord Notification

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]

jobs:
  notify:
    # if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    name: 'CI Status - Discord Notification'
    steps:
      - name: Inspect Event Object
        env:
          EVENT: ${{ toJSON( github.event ) }}
        run: echo $EVENT
      - name: Send Discord message
        env:
          CI_STATUS: ${{ github.event.workflow_run.conclusion }}
          REPO_NAME: ${{ github.event.repository.name }}
          GIT_BRANCH: ${{ github.event.workflow_run.head_branch }}
          WORKFLOW_URL: ${{ github.event.workflow_run.html_url }}
        run: |
          curl \
            -i \
            -H "Accept: application/json" \
            -H "Content-Type:application/json" \
            -X POST \
            --data "{\"content\":\"CI $CI_STATUS $REPO_NAME $GIT_BRANCH $WORKFLOW_URL\",\"username\":\"GitHub\",\"avatar_url\":\"https://i.imgur.com/OOtUMJD.png\"}" \
            https://discord.com/api/webhooks/915965618350612481/JZDe_sBO3kCqUgkKNZ3OZ9q61d2LkW82ozTHoh8W8PV20r4E2y5B9ZpvtMccXP9i-6UC
