name: CI

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
  pull_request:

jobs:
  matrixJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - id: getMatrix
      run: echo "::set-output name=matrix::$(node ./.github/workflows/ci/getMatrix.mjs)"
    - run: echo ${{ steps.getMatrix.outputs.matrix }}
    outputs:
      matrix: ${{ steps.getMatrix.outputs.matrix }}

  test:
    needs: matrixJob
    strategy:
      matrix: ${{fromJson(needs.matrixJob.outputs.matrix)}}
      fail-fast: false
    env:
      TEST_FILES: ${{ matrix.TEST_FILES }}
    runs-on: ${{ matrix.os }}
    name: '${{ matrix.name }}'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Setup
        run: pnpm run setup

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm run test
        env:
          GIT_BRANCH: ${{ github.ref_name }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
